# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true
# Suppress some warnings due to discrepancies between Gramophone JDK (21) and media3 JDK (8)
android.javaCompile.suppressSourceTargetDeprecationWarning=true
# Suppress experimental option warnings
android.suppressUnsupportedOptionWarnings=android.enableAppCompileTimeRClass,android.enableBuildConfigAsBytecode,android.dependencyResolutionAtConfigurationTime.disallow,android.useConditionalKeepRules,android.disableEarlyManifestParsing,android.keepWorkerActionServicesBetweenBuilds,android.enablePartialRIncrementalBuilds,android.experimental.verifyLibraryClasses,android.suppressUnsupportedOptionWarnings
# Gradle
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true

# Build BuildConfig as Bytecode
android.enableBuildConfigAsBytecode=true
# Reduce APK size by only keeping view constructors if layout is used
# TODO: enable this when figuring out why it crashes all AlertDialog inflations.
android.useConditionalKeepRules=false
# Verify library classes
android.experimental.verifyLibraryClasses=true
# Improve build times by using best-practice build scripts
android.dependencyResolutionAtConfigurationTime.disallow=true
android.disableEarlyManifestParsing=true
# Improve build times by keeping AAPT2 daemon alive
android.keepWorkerActionServicesBetweenBuilds=true
# Improve build times by caching r.txt for incremental builds
android.enablePartialRIncrementalBuilds=true
# TODO: remove these later
android.builtInKotlin=false
android.newDsl=false
